codes = [('Á', '&Aacute;'),
('á', '&aacute;'),
('Â', '&Acirc;'),
('â', '&acirc;'),
('À', '&Agrave;'),
('à', '&agrave;'),
('Ã', '&Atilde;'),
('ã','&atilde;'),
('É', '&Eacute;'),
('é', '&eacute;'),
('Ê', '&Ecirc;'),
('ê', '&ecirc;'),
('Í', '&Iacute;'),
('í', '&iacute;'),
('Ó', '&Oacute;'),
('ó', '&oacute;'),
('Ô', '&Ocirc;'),
('ô', '&ocirc;'),
('Õ','&Otilde;'),
('õ','&otilde;'),
('Ú','&Uacute;'),
('ú','&uacute;'),
('Ç','&Ccedil;'),
('ç','&ccedil;')];